#ifndef COLORS_H
#define COLORS_H

// NOTE: 'colormap' is really hue (HSV/HSL color space) but HL uses 1 byte (0...255) range instead of degrees (0...360)

#define COLORMAP_HUE_DELTA12	(256/12)// == 21.33... == 15h

#define HUEBYTE_RED				0x00// COLORMAP_HUE_DELTA12*0
#define HUEBYTE_ORANGE			COLORMAP_HUE_DELTA12*1
#define HUEBYTE_YELLOW			COLORMAP_HUE_DELTA12*2
#define HUEBYTE_LIME			COLORMAP_HUE_DELTA12*3
#define HUEBYTE_GREEN			COLORMAP_HUE_DELTA12*4
#define HUEBYTE_SEAGREEN		COLORMAP_HUE_DELTA12*5
#define HUEBYTE_CYAN			COLORMAP_HUE_DELTA12*6
#define HUEBYTE_SKYBLUE			COLORMAP_HUE_DELTA12*7
#define HUEBYTE_BLUE			COLORMAP_HUE_DELTA12*8
#define HUEBYTE_VIOLET			COLORMAP_HUE_DELTA12*9
#define HUEBYTE_MAGENTA			COLORMAP_HUE_DELTA12*10
#define HUEBYTE_ROSE			COLORMAP_HUE_DELTA12*11

// 2 bytes, both are equal
#define COLORMAP_RED			HUEBYTE_RED			+ (HUEBYTE_RED		<< CHAR_BIT)
#define COLORMAP_ORANGE			HUEBYTE_ORANGE		+ (HUEBYTE_ORANGE	<< CHAR_BIT)
#define COLORMAP_YELLOW			HUEBYTE_YELLOW		+ (HUEBYTE_YELLOW	<< CHAR_BIT)
#define COLORMAP_LIME			HUEBYTE_LIME		+ (HUEBYTE_LIME		<< CHAR_BIT)
#define COLORMAP_GREEN			HUEBYTE_GREEN		+ (HUEBYTE_GREEN	<< CHAR_BIT)
#define COLORMAP_SEAGREEN		HUEBYTE_SEAGREEN	+ (HUEBYTE_SEAGREEN	<< CHAR_BIT)
#define COLORMAP_CYAN			HUEBYTE_CYAN		+ (HUEBYTE_CYAN		<< CHAR_BIT)
#define COLORMAP_SKYBLUE		HUEBYTE_SKYBLUE		+ (HUEBYTE_SKYBLUE	<< CHAR_BIT)
#define COLORMAP_BLUE			HUEBYTE_BLUE		+ (HUEBYTE_BLUE		<< CHAR_BIT)
#define COLORMAP_VIOLET			HUEBYTE_VIOLET		+ (HUEBYTE_VIOLET	<< CHAR_BIT)
#define COLORMAP_MAGENTA		HUEBYTE_MAGENTA		+ (HUEBYTE_MAGENTA	<< CHAR_BIT)
#define COLORMAP_ROSE			HUEBYTE_ROSE		+ (HUEBYTE_ROSE		<< CHAR_BIT)
#define COLORMAP_XHL_LOGO		0x9C54

// The following "colors" are palette indexes (palette.lmp)
#ifndef BLOOD_COLOR_RED
#define	BLOOD_COLOR_RED			(byte)247
#endif

#ifndef BLOOD_COLOR_YELLOW
#define	BLOOD_COLOR_YELLOW		(byte)192
#endif

#ifndef BLOOD_COLOR_GREEN
#define	BLOOD_COLOR_GREEN		(byte)216
#endif

#ifndef BLOOD_COLOR_BLUE
#define	BLOOD_COLOR_BLUE		(byte)208
#endif

#define	BLOOD_COLOR_BLACK		(byte)0//(0,0,0)
#define	BLOOD_COLOR_GRAY		(byte)8//(123,123,123)
#define	BLOOD_COLOR_MAGENTA		(byte)144//(186,116,160)

#define	BLOOD_COLOR_YELLOW1		(byte)195//(204,188,0)
#define	BLOOD_COLOR_YELLOW2		(byte)200//(120,100,0)
#define	BLOOD_COLOR_YELLOW3		(byte)203//(76,56,0)

#define	BLOOD_COLOR_BLUE1		(byte)209//(0,0,238)
#define	BLOOD_COLOR_BLUE2		(byte)210//(0,0,220)
#define	BLOOD_COLOR_BLUE3		(byte)211//(0,0,204)
#define	BLOOD_COLOR_BLUE4		(byte)212//(0,0,186)
#define	BLOOD_COLOR_BLUE5		(byte)213//(0,0,170)
#define	BLOOD_COLOR_BLUE6		(byte)214//(0,0,154)
#define	BLOOD_COLOR_BLUE7		(byte)215//(0,0,136)

#define	BLOOD_COLOR_GREEN1		(byte)217//(0,238,0)
#define	BLOOD_COLOR_GREEN2		(byte)218//(0,220,0)
#define	BLOOD_COLOR_GREEN3		(byte)219//(0,204,0)
#define	BLOOD_COLOR_GREEN4		(byte)220//(0,186,0)
#define	BLOOD_COLOR_GREEN5		(byte)221//(0,170,0)
#define	BLOOD_COLOR_GREEN6		(byte)222//(0,154,0)
#define	BLOOD_COLOR_GREEN7		(byte)223//(0,136,0)

#define	BLOOD_COLOR_HUM_SKN		(byte)239//(246,210,140)
#define	BLOOD_COLOR_CYAN		(byte)245//(160,236,255)

#define	BLOOD_COLOR_RED1		(byte)248//(140,0,0)
#define	BLOOD_COLOR_RED2		(byte)249//(180,0,0)
#define	BLOOD_COLOR_RED3		(byte)250//(216,0,0)
#define	BLOOD_COLOR_RED4		(byte)251//(255,0,0)

#define	BLOOD_COLOR_WHITE		(byte)254//(255,255,255)

#endif // COLORS_H
