#ifndef WEAPONSLOTS_H
#define WEAPONSLOTS_H

#define SLOT_CROWBAR			0
#define SLOT_SWORD				0
#define SLOT_NANOSWORD			0

#define SLOT_GLOCK				1
#define SLOT_PYTHON				1
#define SLOT_CHEMGUN			1

#define SLOT_MP5				2
#define SLOT_SHOTGUN			2
#define SLOT_CROSSBOW			2

#define SLOT_RPG				3
#define SLOT_DLAUNCHER			3
#define SLOT_GLAUNCHER			3
#define SLOT_ALAUNCHER			3

#define SLOT_GAUSS				4
#define SLOT_EGON				4
#define SLOT_PLASMA				4
#define SLOT_FLAME				4

#define SLOT_HANDGRENADE		5
#define SLOT_SATCHEL			5
#define SLOT_TRIPMINE			5
#define SLOT_SNARK				5
#define SLOT_STRTARGET			5// XDM3035a
#define SLOT_ORB				5

#define SLOT_DISPLACER			6
#define SLOT_BEAMRIFLE			6
#define SLOT_PULSERIFLE			6
#define SLOT_HORNETGUN			6


#define POSITION_CROWBAR		0
#define POSITION_SWORD			1
#define POSITION_NANOSWORD		2

#define POSITION_GLOCK			0
#define POSITION_PYTHON			1
#define POSITION_CHEMGUN		2

#define POSITION_MP5			0
#define POSITION_SHOTGUN		1
#define POSITION_CROSSBOW		2

#define POSITION_RPG			0
#define POSITION_GLAUNCHER		1
#define POSITION_ALAUNCHER		2
#define POSITION_DLAUNCHER		3

#define POSITION_GAUSS			0
#define POSITION_EGON			1
#define POSITION_PLASMA			2
#define POSITION_FLAME			3

#define POSITION_HANDGRENADE	0
#define POSITION_SATCHEL		1
#define POSITION_TRIPMINE		2
#define POSITION_SNARK			3
#define POSITION_STRTARGET		4// XDM3035a
#define POSITION_ORB			5

#define POSITION_DISPLACER		0
#define POSITION_BEAMRIFLE		1
#define POSITION_PULSERIFLE		2
#define POSITION_HORNETGUN		3

#endif // WEAPONSLOTS_H
